# Generated by Django 5.0.6 on 2024-05-21 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sifre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vatandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.CharField(max_length=50)),
                ('Soyad', models.CharField(max_length=50)),
                ('DogumTarihi', models.DateField()),
                ('Cinsiyet', models.CharField(max_length=10)),
                ('TelefonNumarasi', models.CharField(max_length=20)),
                ('Adres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Yetkili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.CharField(max_length=50)),
                ('Soyad', models.CharField(max_length=50)),
                ('Gorev', models.CharField(max_length=100)),
                ('CalistigiBirim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarih', models.DateField()),
                ('Saat', models.TimeField()),
                ('Vatandas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vatandas')),
                ('Yetkili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.yetkili')),
            ],
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icerik', models.TextField()),
                ('OkunduMu', models.BooleanField(default=False)),
                ('Tarih', models.DateTimeField(auto_now_add=True)),
                ('Vatandas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vatandas')),
                ('Yetkili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.yetkili')),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaporTarihi', models.DateField()),
                ('RaporIcerigi', models.TextField()),
                ('Vatandas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vatandas')),
                ('Yetkili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.yetkili')),
                ('Yonetici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.yonetici')),
            ],
        ),
    ]
